services:
  redis:
    image: redis:alpine

  tram-predictor:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=9030
      - TZ=Europe/Berlin
    ports:
      - "9030:9030"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis
